"use client";
import type { Profile, Report, Section } from '../types';
import { DAILY_MINUTES, DEFAULT_DAILY_MINUTES } from '../domain/profile';
export default function StudyPlan({report,profile,progress,onProgress,onDailyMinutes}: {report:Report;profile:Profile;progress:Record<string,boolean>;onProgress:(key:string,value:boolean)=>void;onDailyMinutes:(minutes:number)=>void}){
  const sections:Section[]=['Listening','Reading','Grammar'];
  const priorities=report.areas.filter(a=>a.id!=='R_VOCABULARY_OVERALL').sort((a,b)=>a.level-b.level||(b.total-b.correct)-(a.total-a.correct));
  /* Chưa khai thì theo mặc định của đặc tả: 30 phút/ngày. */
  const daily=profile.dailyMinutes||DEFAULT_DAILY_MINUTES;
  const weeks=['Củng cố nội dung ưu tiên','Luyện từng dạng có hướng dẫn','Áp dụng trong bài kết hợp','Kiểm tra lại và điều chỉnh'];
  return <div data-study-plan className="space-y-6"><p className="text-ink/70">Mục tiêu tự khai: {profile.target}. Kế hoạch tập trung vào các câu đã làm, không cam kết tăng band.</p>
    {/* Đổi thời lượng chỉ chia lại khối lượng mỗi buổi, KHÔNG đụng tới điểm hay nhận xét. */}
    <label className="flex flex-wrap items-center gap-3 rounded-xl border border-brand/15 bg-mist-3 p-4 text-sm"><b className="font-bold text-brand">Thời lượng mỗi buổi</b><select className="diag-input !w-auto" value={daily} onChange={e=>onDailyMinutes(Number(e.target.value))}>{DAILY_MINUTES.filter(o=>o.minutes>0).map(o=><option key={o.label} value={o.minutes}>{o.label}</option>)}</select><span className="text-ink/60">Đổi thời lượng chỉ chia lại khối lượng từng buổi; điểm và nhận xét giữ nguyên.</span></label>{report.blanks>0&&<p className="diag-notice">Bạn bỏ trống {report.blanks} câu. Mỗi buổi dành một phần thời gian luyện hoàn thành bài đúng hạn; các câu bỏ trống chưa đủ để kết luận lỗ hổng kiến thức.</p>}
    {weeks.map((week,w)=><section key={week} className="diag-panel"><h3 className="text-xl font-bold text-brand">Tuần {w+1} · {week}</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{Array.from({length:6},(_,d)=>{
      const section=sections[d%3];const group=priorities.filter(a=>a.section===section);const area=group[(Math.floor(d/3)+w)%Math.min(group.length,2)];const key=`week-${w+1}-day-${d+1}`;const focus=area.review.filter(q=>!q.blank);const blank=area.review.filter(q=>q.blank);const minutes=[Math.max(2,Math.round(daily/6)),Math.round(daily/3)];const practice=daily-minutes[0]-minutes[1];
      const exercise=section==='Grammar'?'Viết và giải thích các câu ví dụ mới dùng cấu trúc này.':section==='Reading'?'Đọc một đoạn tiếng Anh mới cùng dạng; gạch căn cứ, tóm tắt và nối các cụm từ đồng nghĩa.':'Nghe một đoạn hội thoại mới cùng dạng; dự đoán thông tin, ghi đáp án rồi kiểm tra lại với bản ghi hoặc giáo viên.';
      return <article key={key} className="min-w-0 rounded-xl border border-brand/15 bg-white p-4"><label className="flex items-start gap-3"><input type="checkbox" aria-label={`Tuần ${w+1}, ngày ${d+1}: ${section} — ${area.name}`} checked={!!progress[key]} onChange={e=>onProgress(key,e.target.checked)} className="mt-1 h-5 w-5 shrink-0 accent-brand"/><span className="min-w-0"><b>Ngày {d+1} · {section}</b><span className="block break-words text-sm text-ink/65">{area.name}</span></span></label><p className="my-3 text-sm">Căn cứ: đúng {area.correct}/{area.total} câu. {area.level===2?'Duy trì nội dung đã làm tốt.':focus.length?`Ưu tiên: ${focus.map(q=>q.id).join(', ')}.`:'Làm lại các câu chưa trả lời để kiểm tra thêm.'}</p>
      <ol className="ml-4 list-decimal space-y-2 text-sm leading-relaxed"><li>{minutes[0]} phút: {focus.length?`Xem lại ${focus.map(q=>q.id).join(', ')} và lời giải.`:blank.length?`Thử làm lại ${blank.map(q=>q.id).join(', ')}.`:'Ôn lại cách làm và căn cứ ở các câu đã đúng.'}</li><li>{minutes[1]} phút: {w===0?'Ôn kiến thức và cách tiếp cận.':w===1?'Luyện từng dạng; ghi lý do chọn đáp án.':w===2?'Làm bài kết hợp với giới hạn thời gian.':'Làm mini-test bằng câu mới cùng dạng.'} {exercise}</li><li>{practice} phút: {w===3?'So sánh kết quả mới, ghi lại thay đổi và chọn nội dung ôn tiếp.':'Kiểm tra bài; ghi lỗi thực tế và cách sửa, sau đó làm lại không nhìn đáp án.'}</li></ol>
      <p className="mt-3 text-sm text-ink/65">Sản phẩm: một trang ghi chép gồm bài làm, căn cứ và điều cần nhớ. Tài liệu: đề và lời giải bên trên; chọn thêm bài mới cùng dạng hoặc nhờ giáo viên cung cấp.</p>{focus.length>0&&<details className="mt-3 text-sm"><summary className="cursor-pointer text-brand">Nội dung ôn từ bài của bạn</summary><ul className="mt-2 space-y-1">{focus.map(q=><li key={q.id}>{q.id}: {q.text}</li>)}</ul></details>}</article>;
    })}</div></section>)}
  </div>;
}
